---
- name: Create VM from a template
  hosts: localhost
#  vars:
#    datacenter: 'datacenter1'
#    esxi_host: '192.168.1.136'
#    notes: 'Created by Ansible'
#    vcenter_hostname: 192.168.1.136
#    vcenter_user: root
#    vcenter_pass: Kikou1012$
#    datastore: datastore1
#    network: VM Network
#    memory: 10
#    cpucount: 1
#    osid: debin6_64Guest
  vars:
    name:
    datacenter:
    notes:
    vcenter_user:
    vcenter_hostname:
    memory-mb:
    cpu:
    vcenter_pass
  tasks:
  - name: Create a VM from template
    vmware_guest:
      hostname: "{{ name }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: no
      name: VM1
      state: present
      #template: vm1
      disk:
      - size_gb: 1
        type: thin
        datastore: "{{ datacenter }}"
      hardware:
        memory_mb: "{{ memory-mb }}"
        num_cpus: "{{ cpu }}"
        scsi: paravirtual
      wait_for_ip_address: no
      folder: /
      guest_id: centos64guest
    #register: deploy
    
