---
- name: Maintenance on TSE
  hosts: windows
  vars:
    Message: Toto
  tasks:
  - name: Ping TSE
    win_ping:
  - name: send msg
    win_shell: msg.exe /server:192.168.1.129 * "{{ Message }}"                                                
